### PR TITLE
feat: sort array of links

### PR DESCRIPTION
**Pull request by porkus1990**
::FESH-611

### CODE REVIEW

**Comment by porkus1990** [comment]
yes, we can talk about the 🚀 - i like the emojis but we can get rid of them in every repo so we can get rid of 2 array.map()

but, personally: emojis - yeah

**Comment by porkus1990** [comment]
add remaining body @porkus1990

**Comment by Tom-El-Egant** [comment]
> yes, we can talk about the 🚀 - i like the emojis but we can get rid of them in every repo so we can get rid of 2 array.map()
> 
> but, personally: emojis - yeah
> 
> hm.. looking at the code again.. maybe we should get rid of the emojis or at least: add a new param (emoji) and make it dynamic
> 
> what do you think? or don't you care?

To be honest - I don't care 😅  We could get rid of them, place one on top of the message, include them twice in each line - doesn't matter to me ;-)

**Review by Tom-El-Egant — APPROVED** [review]

**Comment by JennyZeiser** [comment]
> 

Personally, I don't need these emojis, but I don't care if we keep it or not.

**Review by JennyZeiser — APPROVED** [review]

**Pull request merged**
